In [ ]:
#NumPy (Numerical Python) is an open-source Python library used for numerical and scientific computing
#Supports 1D, 2D, 3D, and higher-dimensional arrays.
#Uses less memory because all elements have the same data type
#ndim returns the number of dimensions (axes) of the array.
#shape returns the size of the array in each dimension.
#size returns the total number of elements in the array.
#dtype returns the data type of the elements stored in the array.
#type() returns the type of the object.
#Python List	Part of Python's built-in data types
##NumPy Array Part of Python's built-in data types
#shape returns the dimensions of the array
#size Returns the total number of elements
#dtype Returns the data type of the array elements
#type()	Returns the type of the object
#In a 3D NumPy array, the shape is written as (a, b, c).
#a - Number of matrices
#b - Number of rows in each matrix
#c - Number of columns in each row


In [4]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [5]:
a.ndim

1

In [6]:
a.shape

(12,)

In [7]:
a.size

12

In [8]:
a.dtype

dtype('int64')

In [10]:
type(a)

numpy.ndarray

In [14]:
b=np.array(
    [
      
    [
 [ 0 ,1 , 2],
 [ 3 , 4 , 5],
 [ 6,  7 , 8],
 [ 9, 10 ,11],
 [12, 13 ,14],
 [15, 16 ,17]
 ]
    ]
)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [15]:
b.ndim

2

In [16]:
b.shape

(6, 3)

In [17]:
b.size

18

In [18]:
b.dtype

dtype('int64')

In [19]:
type(b)

numpy.ndarray

In [25]:
c = np.array([
    [
        [0, 1],
        [2, 3],
        [4, 5],
        [6, 7]
    ],
    [
        [8, 9],
        [10, 11],
        [12, 13],
        [14, 15]
    ],
    [
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]
    ]
])

print(c)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [26]:
c.ndim

3

In [27]:
c.shape

(3, 4, 2)

In [28]:
c.size

24

In [29]:
c.dtype

dtype('int64')

In [30]:
type(c)

numpy.ndarray

In [34]:
d = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ],
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ],
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ],
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ],
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ],
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ]
])

print(d)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [35]:
d.ndim

3

In [36]:
d.shape

(6, 2, 4)

In [37]:
d.size

48

In [38]:
d.dtype

dtype('int64')