In [1]:
import numpy as np
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
b=a.reshape(9,)
print(b)

[1 2 3 4 5 6 7 8 9]


In [3]:
c=np.array([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
print(c)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [4]:
d=c.flatten()
print(d)

[1 2 3 4 5 6 7 8 9]


In [5]:
arr=np.array([
    [
        [1,2],
        [3,4]],
    [
        [3,4],
        [5,6]
        ],
    [
        [6,7],
        [8,9]
        ]
])
print(arr)
arr2=arr.reshape(-1)
print(arr2)

        

[[[1 2]
  [3 4]]

 [[3 4]
  [5 6]]

 [[6 7]
  [8 9]]]
[1 2 3 4 3 4 5 6 6 7 8 9]


In [6]:
c=np.array([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
c.shape

(1, 3, 3)

In [7]:
d=c.flatten()
print(d)

[1 2 3 4 5 6 7 8 9]


In [8]:
d.shape

(9,)

In [11]:
arr=np.array([
    [10,20],
    [30,40],
    [50,60]
])
print(arr)
arr2=arr.flatten()
print(arr2)

[[10 20]
 [30 40]
 [50 60]]
[10 20 30 40 50 60]


In [12]:
d=np.array([1,2,3,4,5,6,7,8])
c=d.reshape(2,4)
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
dd=d.reshape(1,2,4)
print(dd)

[[[1 2 3 4]
  [5 6 7 8]]]


In [14]:
a=np.array([2,4,6])
b=np.array([1,3,5])
c=np.add(a,b)
c


array([ 3,  7, 11])

In [15]:
c=np.dot(a,b)
c

np.int64(44)

In [16]:
c=np.subtract(a,b)
c


array([1, 1, 1])

In [17]:
c=np.multiply(a,b)
c

array([ 2, 12, 30])

In [18]:
c=np.divide(a,b)
c

array([2.        , 1.33333333, 1.2       ])

In [22]:
a=np.array([12,5,30,18,9])
a.max()


np.int64(30)

In [21]:
a.min()

np.int64(5)

In [23]:
a.mean()

np.float64(14.8)

In [25]:
a.argmax()

np.int64(2)

In [26]:
a.argmin()

np.int64(1)

In [27]:
a=np.array([
    [1,2,3],
    [4,5,6]
])
a.max(axis=0)

array([4, 5, 6])

In [28]:
a.max(axis=1)

array([3, 6])

In [29]:
a.min(axis=0)

array([1, 2, 3])

In [30]:
a.min(axis=1)

array([1, 4])

In [32]:
a.sum(0)

array([5, 7, 9])

In [33]:
a.sum(1)

array([ 6, 15])

In [34]:
a=np.array([5,10,15,20,25,30])
print(a[0])

5


In [37]:
print(a[-1])

30


In [38]:
print(a[1:4])

[10 15 20]


In [41]:
print(a[0:4])

[ 5 10 15 20]


In [43]:
print(a[1::2])

[10 20 30]


In [54]:
print(a[-1:-6])

[]


In [58]:
a[::-1]

array([30, 25, 20, 15, 10,  5])

In [59]:
a=np.array([ [1,2,3], [4,5,6], [7,8,9] ]) 
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
print( a[1, 2])

6


In [61]:
print( a[0])

[1 2 3]


In [66]:
print( a[:,1])


[2 5 8]


In [67]:
print(a[-1])

[7 8 9]


In [68]:
print(a[:2])

[[1 2 3]
 [4 5 6]]


In [69]:
print(a[1:, 1:])

[[5 6]
 [8 9]]


In [70]:
a = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [71]:
print(a[0])

[[1 2 3]
 [4 5 6]]


In [72]:
print(a[1])

[[ 7  8  9]
 [10 11 12]]


In [73]:
print(a[0, 0])

[1 2 3]


In [74]:
print(a[1, 1])

[10 11 12]


In [75]:
print(a[1, 1, 1])

11


In [76]:
print(a[-1, -1, -1])

12


In [77]:
a = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [78]:
print(a[0])

[[1 2 3]
 [4 5 6]]


In [79]:
a[:,0]

array([[1, 2, 3],
       [7, 8, 9]])

In [80]:
print(a[:,:,1])

[[ 2  5]
 [ 8 11]]


In [81]:
print(a[:,:,1:])

[[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]


In [82]:
print(a[:,:,:2])

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [83]:
print(a[:,:,::-1])

[[[ 3  2  1]
  [ 6  5  4]]

 [[ 9  8  7]
  [12 11 10]]]


In [84]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [86]:
print(a[:2, :2])

[[1 2]
 [5 6]]


In [87]:
print(a[:2, 2:])

[[3 4]
 [7 8]]


In [88]:
print(a[1:3, 1:3])

[[ 6  7]
 [10 11]]


In [89]:
print(a[1:3, 1:3])

[[ 6  7]
 [10 11]]


In [90]:
print(a[1:3, :3])

[[ 5  6  7]
 [ 9 10 11]]


In [91]:
print(a[:3, 1:3])

[[ 2  3]
 [ 6  7]
 [10 11]]


In [92]:
print(a[2:3, :])

[[ 9 10 11 12]]


In [93]:
print(a[:, 3:4])

[[ 4]
 [ 8]
 [12]
 [16]]


In [94]:
print(a[::2, ::2])

[[ 1  3]
 [ 9 11]]


In [95]:
print(a[1:, 1:])

[[ 6  7  8]
 [10 11 12]
 [14 15 16]]
